### ISSUE TITLE
Model not proven fully for > 2 circles

### ISSUE THREAD

**Issue by pvitkovsky** [pvitkovsky/three_circles_intersection#3]
Look in model.testCommonPoint;
In properly simplified 3 circle model, if there is no Type.none and no Type.contact, there must be only Type.intersection. 
But it is not proven that if each of n circles intersect each ther, a common point must exist.

**Comment by GalimovDenis** [comment]
I corrected it, but i had problem with connection to GitHub.

пн, 4 Июн 2018, 4:46 pvitkovsky <notifications@github.com>:

**Comment by pvitkovsky** [comment]
I wanted to ask about maths. If {c : circles} intersects with each of {circles}, is it proven that the common point exists?

**Comment by GalimovDenis** [comment]
No

**Comment by pvitkovsky** [comment]
Rewrote the model testing each intersection point
